// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nibo.Data;

namespace Nibo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200614212954_transactions")]
    partial class transactions
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Nibo.Models.Import", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date")
                        .HasMaxLength(6);

                    b.Property<string>("FileDuplicate")
                        .IsRequired();

                    b.Property<string>("FileImported")
                        .IsRequired();

                    b.Property<int>("TotalTransactions");

                    b.Property<int>("TotalTransactionsDuplicates");

                    b.Property<int>("TotalTransactionsSaves");

                    b.HasKey("Id");

                    b.ToTable("Import");
                });

            modelBuilder.Entity("Nibo.Models.Transaction", b =>
                {
                    b.Property<string>("Hash")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Memo")
                        .IsRequired();

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(6);

                    b.Property<decimal>("Value");

                    b.HasKey("Hash");

                    b.ToTable("Transaction");
                });
#pragma warning restore 612, 618
        }
    }
}
